#!/usr/bin/env bash
#
# gen_voice.sh — turn a line of text into a Clawdmeter voice header.
#
# The daily-voice feature plays two embedded PCM clips (morning + evening).
# This script regenerates one of those headers from text you type, in any
# language, so you can customize the greetings without hand-editing byte arrays.
#
# Pipeline: Google Translate TTS (free, no key) -> mp3 chunks -> ffmpeg concat
#           -> 12 kHz / 16-bit / mono raw PCM -> C header with the right symbol
#           names (voice_<slot>_pcm[] / voice_<slot>_pcm_len).
#
# Usage:
#   tools/gen_voice.sh morning en "Good morning! Have a productive day."
#   tools/gen_voice.sh evening uk "Добрий вечір. Час відпочивати."
#
# Then reflash:  ./flash-mac.sh waveshare_amoled_216
#
# Requires: bash, curl, ffmpeg, python3.  (ffmpeg:  brew install ffmpeg)
#
set -euo pipefail

SLOT="${1:-}"       # morning | evening  (which clip to replace)
LANG="${2:-}"       # TTS language code: en, uk, es, de, fr, ...
TEXT="${3:-}"       # the sentence(s) to speak

if [[ "$SLOT" != "morning" && "$SLOT" != "evening" ]] || [[ -z "$LANG" || -z "$TEXT" ]]; then
  echo "usage: $0 <morning|evening> <lang-code> \"text to speak\"" >&2
  echo "example: $0 morning en \"Good morning! Have a productive day.\"" >&2
  exit 2
fi

for bin in curl ffmpeg python3; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: '$bin' not found on PATH" >&2; exit 1; }
done

SRC_DIR="$(cd "$(dirname "$0")/../firmware/src" && pwd)"
OUT_H="$SRC_DIR/voice_${SLOT}_pcm.h"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Google Translate TTS caps each request near ~200 chars, so split on sentence
# boundaries and fetch the pieces, then concatenate the audio.
python3 - "$TEXT" > "$WORK/chunks.txt" <<'PY'
import re, sys
text = sys.argv[1]
parts, cur = [], ""
for tok in re.split(r'(?<=[.!?])\s+', text.strip()):
    if len(cur) + len(tok) + 1 > 190:
        if cur: parts.append(cur.strip())
        cur = tok
    else:
        cur = (cur + " " + tok).strip()
if cur: parts.append(cur.strip())
print("\n".join(p for p in parts if p))
PY

i=0
: > "$WORK/list.txt"
while IFS= read -r chunk; do
  [[ -z "$chunk" ]] && continue
  part="$WORK/part_$i.mp3"
  # curl (not urllib): some Python builds fail Google's TLS cert chain.
  curl -sG "https://translate.google.com/translate_tts" \
       --data-urlencode "q=${chunk}" \
       --data "ie=UTF-8&tl=${LANG}&client=tw-ob" \
       -H "User-Agent: Mozilla/5.0" \
       -o "$part"
  echo "file '$part'" >> "$WORK/list.txt"
  i=$((i+1))
done < "$WORK/chunks.txt"

[[ "$i" -eq 0 ]] && { echo "error: no speakable text" >&2; exit 1; }

# Concatenate, then resample to the firmware's native voice format:
# 12 kHz, signed 16-bit little-endian, mono, raw (headerless) PCM.
ffmpeg -v error -f concat -safe 0 -i "$WORK/list.txt" \
       -ar 12000 -ac 1 -f s16le "$WORK/voice.pcm"

# Emit the C header with the exact symbol names the firmware includes.
python3 - "$WORK/voice.pcm" "$SLOT" "$OUT_H" <<'PY'
import sys
pcm, slot, out = sys.argv[1], sys.argv[2], sys.argv[3]
data = open(pcm, "rb").read()
name = f"voice_{slot}_pcm"
with open(out, "w") as f:
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("// Generated by tools/gen_voice.sh — 12 kHz / 16-bit / mono PCM.\n")
    f.write(f"static const uint8_t {name}[] = {{\n")
    for j in range(0, len(data), 20):
        f.write("  " + ",".join(str(b) for b in data[j:j+20]) + ",\n")
    f.write("};\n")
    f.write(f"static const unsigned int {name}_len = {len(data)};\n")
print(f"wrote {out}  ({len(data)} bytes PCM, ~{len(data)/2/12000:.1f}s)")
PY

echo "Done. Reflash to hear it:  ./flash-mac.sh waveshare_amoled_216"
